Repository AY2425S2-CS2103T-W09-1/tp, pull requests merged in 2025-03, with the labels that each got.

#51 Implement support for identifying contacts using identifiers
  src/main/java/seedu/address/model/person/EmailMatchesKeywordPredicate.java
  src/main/java/seedu/address/model/person/IdentifierPredicate.java
  src/main/java/seedu/address/model/person/NameMatchesKeywordPredicate.java
  src/main/java/seedu/address/model/person/PhoneMatchesKeywordPredicate.java
Labels: type.Task, priority.High

#63 Implement Update command to set application status of applicants in the system
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Status.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Story, priority.High

#77 Edit Person card format
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Enhancement, priority.Medium, priority.Low

#75 Branch fix checkstyle
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/applicant/UniquePersonList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedApplicant.java
Labels: type.Bug, priority.Medium, priority.Low

#81 Fix searchCommand and add new predicates
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/model/applicant/JobPositionMatchesPredicate.java
  src/main/java/seedu/address/model/applicant/StatusMatchesPredicate.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
Labels: type.Story, type.Bug, priority.High

#84 Edit search command user guide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
Labels: type.Enhancement, type.Bug, priority.Medium

#93 Update UserGuide to include UpdateCommand
  docs/UserGuide.md
  docs/images/updateCommand_after.png
  docs/images/updateCommand_before.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditApplicantDescriptorTest.java
  src/test/java/seedu/address/model/applicant/ApplicantTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: type.Task, priority.Medium

#96 Add job position and status as contact identifiers for deletion
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
Labels: type.Story, priority.High

#102 Branch search test fix
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/model/applicant/EmailMatchesKeywordPredicate.java
  src/main/java/seedu/address/model/applicant/NameMatchesKeywordPredicate.java
  src/main/java/seedu/address/model/applicant/PhoneMatchesKeywordPredicate.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Medium

#103 Implement Export CSV functionality
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
Labels: priority.High

#109 Add before date and after date as identifiers for delete command
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/applicant/AfterDatePredicate.java
  src/main/java/seedu/address/model/applicant/Applicant.java
  src/main/java/seedu/address/model/applicant/BeforeDatePredicate.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: type.Story, priority.Medium

#118 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/rateCommand_after.png
  docs/images/rateCommand_before.png
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/applicant/UniqueApplicantList.java
  src/test/java/seedu/address/model/applicant/UniqueApplicantListTest.java
Labels: type.Task, priority.High

#120 Update Developer & User Guide
  build.gradle
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ExportSequenceDiagram.puml
  docs/diagrams/SearchSequenceDiagram.puml
Labels: severity.Medium
