Repository AY2425S2-CS2103T-W09-1/tp, pull requests merged in 2025-04, with the labels that each got.

#131 Polish UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#137 Add javadoc for all commands' methods
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/SummaryCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority.Low, severity.Low, alpha-bug

#134 Add a checker method for export command
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Enhancement, severity.Low, alpha-bug

#139 Remove unused code in delete command
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
Labels: type.Bug, priority.Low, alpha-bug

#145 Remove export pop-up window
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.Low, severity.Low, alpha-bug

#138 Update UserGuide
  docs/UserGuide.md
  docs/images/addCommand_after.png
  docs/images/addCommand_before.png
  docs/images/deleteCommand.png
  docs/images/deleteCommand_after.png
  docs/images/deleteCommand_before.png
  docs/images/deleteConfirmation.png
  docs/images/editCommand_after.png
  docs/images/editCommand_before.png
  docs/images/helpScreen.png
  docs/images/rateCommand_after.png
  docs/images/rateCommand_before.png
  docs/images/searchCommand_after.png
  docs/images/searchCommand_before.png
  docs/images/sortCommandByNameAfter.png
  docs/images/sortCommandByNameBefore.png
  docs/images/sortCommand_after.png
  docs/images/sortCommand_before.png
  docs/images/summary.png
  docs/images/updateCommand_after.png
  docs/images/updateCommand_before.png
  src/main/resources/images/profile_photos/alex-yeoh.png
  src/main/resources/images/profile_photos/amy-lee.png
  src/main/resources/images/profile_photos/david-li.png
  src/main/resources/images/profile_photos/john-doe.jpg
Labels: type.Task, priority.Medium

#146 Add address, rating and time to export csv
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.Medium, severity.Medium, alpha-bug

#170 Refine search & summary & delete & update commands
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ConfirmationRequiredCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/commands/SummaryCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SearchCommandParser.java
  src/main/java/seedu/address/logic/parser/SummaryCommandParser.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/applicant/Address.java
  src/main/java/seedu/address/model/applicant/Email.java
  src/main/java/seedu/address/model/applicant/EmailMatchesKeywordPredicate.java
  src/main/java/seedu/address/model/applicant/JobPosition.java
  src/main/java/seedu/address/model/applicant/Name.java
  src/main/java/seedu/address/model/applicant/Phone.java
  src/main/java/seedu/address/model/applicant/UniqueApplicantList.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#171 Add input length check
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.Medium, severity.Medium, alpha-bug

#172 Fix back to top anchors
  docs/UserGuide.md
Labels: priority.Medium, severity.Low, alpha-bug

#160 Fix clear command doesn't remove all the applicant photos in the data file
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/applicant/Applicant.java
  src/main/java/seedu/address/model/applicant/UniqueApplicantList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: priority.Medium, alpha-bug

#175 Fix checkstyle errors
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/commands/RateCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/RateCommandParser.java
  src/main/java/seedu/address/model/applicant/EmailMatchesKeywordPredicate.java
  src/main/java/seedu/address/model/applicant/NameMatchesKeywordPredicate.java
  src/main/java/seedu/address/model/applicant/PhoneMatchesKeywordPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditApplicantDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/RateCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/address/model/applicant/ApplicantTest.java
  src/test/java/seedu/address/model/applicant/JobPositionTest.java
  src/test/java/seedu/address/model/applicant/RatingTest.java
  src/test/java/seedu/address/model/applicant/StatusTest.java
  src/test/java/seedu/address/model/applicant/UniqueApplicantListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedApplicantTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.Low, severity.Low, alpha-bug

#176 Add test cases for delete command and delete command parser
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ConfirmationRequiredCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Bug, priority.High, alpha-bug

#177 Fix inaccurate information in UserGuide
  docs/UserGuide.md
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.High, severity.Medium, alpha-bug

#178 Update User Guide to reflect changes to UpdateCommand
  docs/UserGuide.md
  docs/images/updateCommand_after.png
  docs/images/updateCommand_before.png
Labels: priority.High, severity.Medium

#180 Change user guide for Search
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SearchCommand.java
Labels: priority.Low, severity.Low, alpha-bug

#182 Update UG
  docs/UserGuide.md
Labels: alpha-bug

#232 Light mode for help menu window
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, alpha-bug

#233 Fix bugs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
Labels: type.Bug, priority.Medium, severity.Medium

#237 Clarify sorting case sensitivity in UG
  docs/UserGuide.md
Labels: priority.Low

#238 Add invalid file format for export
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
Labels: priority.Low, severity.Low

#239 Fix issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/RateCommand.java
Labels: priority.High, severity.High

#242 Fix remaining bugs in PE-D
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug, priority.Medium, severity.Medium

#241 Add line breaks when displaying applicant details to improve readability
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ConfirmationRequiredCommand.java
Labels: type.Enhancement, priority.Medium, severity.Low

#240 Bug fixes for UserGuide
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.Medium

#249 Documentation bug fix
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/addCommand_result.png
  docs/images/deleteCommand_result.png
  docs/images/editCommand_result.png
  docs/images/rateCommand_result.png
  docs/images/rateCommand_start.png
  docs/images/searchCommand_result.png
  docs/images/sortCommand_result.png
  docs/images/updateCommand_result.png
Labels: type.Bug, priority.Medium, severity.Low

#251 Fix various bugs
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/applicant/Email.java
Labels: type.Bug, priority.Medium, severity.Medium

#252 Fix update command bug
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ConfirmationRequiredCommand.java
Labels: priority.Medium

#253 Fix hyperlinks in Site Map and User Guide
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
Labels: type.Bug, priority.Medium, severity.Low

#260 Fix update, rate and edit commands to show edited details correctly
  src/main/java/seedu/address/model/applicant/Applicant.java
  src/main/java/seedu/address/model/applicant/UniqueApplicantList.java
Labels: type.Bug, priority.High, severity.Medium

#254 Fix checkstyle in build.gradle
  build.gradle
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/SearchCommand.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Labels: type.Bug, priority.Low, severity.Low

#261 Fix test cases for update command
  src/test/java/seedu/address/logic/commands/UpdateCommandTest.java
Labels: type.Bug, priority.Medium, severity.Medium

#262 Fix failing test cases
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/commands/RateCommandTest.java
  src/test/java/seedu/address/logic/commands/SearchCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
Labels: type.Bug, priority.High, severity.Medium

#264 Add line breaks in UG
  docs/UserGuide.md
Labels: type.Bug, priority.Low, severity.Low

#266 Fix checkstyle errors
  src/main/java/seedu/address/model/applicant/Applicant.java
  src/main/java/seedu/address/model/applicant/Rating.java
  src/test/java/seedu/address/logic/commands/RateCommandTest.java
  src/test/java/seedu/address/logic/commands/SummaryCommandTest.java
  src/test/java/seedu/address/logic/parser/SummaryCommandParserTest.java
Labels: priority.Low, severity.High

#267 Fix test case related issues
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SearchCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.Low, severity.Low

#268 Add line breaks
  docs/DeveloperGuide.md
Labels: priority.Low

#270 Update screenshots to match new UI
  docs/UserGuide.md
  docs/images/addCommand_result.png
  docs/images/deleteCommand_result.png
  docs/images/editCommand_result.png
  docs/images/rateCommand_result.png
  docs/images/rateCommand_start.png
  docs/images/updateCommand_result.png
Labels: type.Task, priority.Low, severity.VeryLow, severity.Low
